const pecas = [
  {
    id: '1',
    nome: 'Parafuso Hexagonal',
    maquina: 'Torno CNC',
    descricao: 'Parafuso de aço inox M12',
    numeroFabricante: 'PF-001',
    codigoCompra: 'CH-129843',
    localizacao: 'G12B3A1',
  },
  {
    id: '2',
    nome: 'Engrenagem Principal',
    maquina: 'Fresadora',
    descricao: 'Engrenagem helicoidal 45 dentes',
    numeroFabricante: 'EG-002',
    codigoCompra: 'CP-837612',
    localizacao: 'G12B3A2',
  },
  {
    id: '3',
    nome: 'Correia Dentada',
    maquina: 'Prensa Hidráulica',
    descricao: 'Correia de borracha reforçada',
    numeroFabricante: 'CR-003',
    codigoCompra: 'CH-623478',
    localizacao: 'G12B3A3',
  },
  {
    id: '4',
    nome: 'Rolamento Esférico',
    maquina: 'Esteira Transportadora',
    descricao: 'Rolamento de alta resistência',
    numeroFabricante: 'RL-004',
    codigoCompra: 'CP-198274',
    localizacao: 'G12B3A4',
  },
  {
    id: '5',
    nome: 'Pistão Hidráulico',
    maquina: 'Prensa Hidráulica',
    descricao: 'Pistão de aço carbono',
    numeroFabricante: 'PH-005',
    codigoCompra: 'CH-453672',
    localizacao: 'G12B3A5',
  },
  {
    id: '6',
    nome: 'Válvula de Controle',
    maquina: 'Compressor de Ar',
    descricao: 'Válvula de alta precisão',
    numeroFabricante: 'VC-006',
    codigoCompra: 'CP-728316',
    localizacao: 'G12B3A6',
  },
  {
    id: '7',
    nome: 'Filtro de Óleo',
    maquina: 'Gerador',
    descricao: 'Filtro de alta eficiência',
    numeroFabricante: 'FO-007',
    codigoCompra: 'CH-937215',
    localizacao: 'G12B3A7',
  },
  {
    id: '8',
    nome: 'Motor Elétrico',
    maquina: 'Torno CNC',
    descricao: 'Motor trifásico 220V',
    numeroFabricante: 'ME-008',
    codigoCompra: 'CP-518374',
    localizacao: 'G12B3A8',
  },
  {
    id: '9',
    nome: 'Sensor de Temperatura',
    maquina: 'Caldeira',
    descricao: 'Sensor digital de alta precisão',
    numeroFabricante: 'ST-009',
    codigoCompra: 'CH-652839',
    localizacao: 'G12B3A9',
  },
  {
    id: '10',
    nome: 'Eixo Principal',
    maquina: 'Fresadora',
    descricao: 'Eixo de aço temperado',
    numeroFabricante: 'EP-010',
    codigoCompra: 'CP-312478',
    localizacao: 'G12B3A10',
  },
  {
    id: '11',
    nome: 'Chave de Torque',
    maquina: 'Torno CNC',
    descricao: 'Chave ajustável 10-100 Nm',
    numeroFabricante: 'CT-011',
    codigoCompra: 'CH-219847',
    localizacao: 'G12B3A11',
  },
  {
    id: '12',
    nome: 'Bucha de Bronze',
    maquina: 'Esteira Transportadora',
    descricao: 'Bucha autolubrificante',
    numeroFabricante: 'BB-012',
    codigoCompra: 'CP-427639',
    localizacao: 'G12B3A12',
  },
  {
    id: '13',
    nome: 'Mangueira Flexível',
    maquina: 'Compressor de Ar',
    descricao: 'Mangueira de alta pressão',
    numeroFabricante: 'MF-013',
    codigoCompra: 'CH-827364',
    localizacao: 'G12B3A13',
  },
  {
    id: '14',
    nome: 'Interruptor de Segurança',
    maquina: 'Prensa Hidráulica',
    descricao: 'Interruptor de emergência',
    numeroFabricante: 'IS-014',
    codigoCompra: 'CP-673281',
    localizacao: 'G12B3A14',
  },
  {
    id: '15',
    nome: 'Rotor de Ventilação',
    maquina: 'Compressor de Ar',
    descricao: 'Rotor de alumínio fundido',
    numeroFabricante: 'RV-015',
    codigoCompra: 'CH-937451',
    localizacao: 'G12B3A15',
  },
  {
    id: '16',
    nome: 'Amortecedor de Vibração',
    maquina: 'Gerador',
    descricao: 'Amortecedor de borracha industrial',
    numeroFabricante: 'AV-016',
    codigoCompra: 'CP-287164',
    localizacao: 'G12B3A16',
  },
  {
    id: '17',
    nome: 'Disco de Corte',
    maquina: 'Torno CNC',
    descricao: 'Disco de aço temperado',
    numeroFabricante: 'DC-017',
    codigoCompra: 'CH-184763',
    localizacao: 'G12B3A17',
  },
  {
    id: '18',
    nome: 'Placa de Controle',
    maquina: 'Caldeira',
    descricao: 'Placa eletrônica integrada',
    numeroFabricante: 'PC-018',
    codigoCompra: 'CP-836472',
    localizacao: 'G12B3A18',
  },
  {
    id: '19',
    nome: 'Ventoinha',
    maquina: 'Gerador',
    descricao: 'Ventoinha de aço inox',
    numeroFabricante: 'VT-019',
    codigoCompra: 'CH-564738',
    localizacao: 'G12B3A19',
  },
  {
    id: '20',
    nome: 'Resistor de Potência',
    maquina: 'Fresadora',
    descricao: 'Resistor de cerâmica 200W',
    numeroFabricante: 'RP-020',
    codigoCompra: 'CP-729183',
    localizacao: 'G12B3A20',
  },
  {
    id: '21',
    nome: 'Chapa de Proteção',
    maquina: 'Caldeira',
    descricao: 'Chapa de aço galvanizado',
    numeroFabricante: 'CP-021',
    codigoCompra: 'CH-627819',
    localizacao: 'G12B3A21',
  },
  {
    id: '22',
    nome: 'Parafuso de Ajuste',
    maquina: 'Prensa Hidráulica',
    descricao: 'Parafuso com rosca fina',
    numeroFabricante: 'PA-022',
    codigoCompra: 'CP-817263',
    localizacao: 'G12B3A22',
  },
  {
    id: '23',
    nome: 'Mola de Compressão',
    maquina: 'Compressor de Ar',
    descricao: 'Mola de aço de alta resistência',
    numeroFabricante: 'MC-023',
    codigoCompra: 'CH-927351',
    localizacao: 'G12B3A23',
  },
  {
    id: '24',
    nome: 'Cabo de Alimentação',
    maquina: 'Gerador',
    descricao: 'Cabo trifásico 5m',
    numeroFabricante: 'CA-024',
    codigoCompra: 'CP-729384',
    localizacao: 'G12B3A24',
  },
  {
    id: '25',
    nome: 'Termômetro Digital',
    maquina: 'Caldeira',
    descricao: 'Termômetro com display LED',
    numeroFabricante: 'TD-025',
    codigoCompra: 'CH-837261',
    localizacao: 'G12B3A25',
  },
  {
    id: '26',
    nome: 'Conector Elétrico',
    maquina: 'Torno CNC',
    descricao: 'Conector de alta condução',
    numeroFabricante: 'CE-026',
    codigoCompra: 'CP-928374',
    localizacao: 'G12B3A26',
  },
  {
    id: '27',
    nome: 'Ventilador Industrial',
    maquina: 'Compressor de Ar',
    descricao: 'Ventilador axial 220V',
    numeroFabricante: 'VI-027',
    codigoCompra: 'CH-736291',
    localizacao: 'G12B3A27',
  },
  {
    id: '28',
    nome: 'Fusível de Proteção',
    maquina: 'Gerador',
    descricao: 'Fusível de 15A',
    numeroFabricante: 'FP-028',
    codigoCompra: 'CP-291847',
    localizacao: 'G12B3A28',
  },
  {
    id: '29',
    nome: 'Guia Linear',
    maquina: 'Fresadora',
    descricao: 'Guia de aço com precisão milimétrica',
    numeroFabricante: 'GL-029',
    codigoCompra: 'CH-512784',
    localizacao: 'G12B3A29',
  },
  {
    id: '30',
    nome: 'Bomba Hidráulica',
    maquina: 'Prensa Hidráulica',
    descricao: 'Bomba de alta pressão',
    numeroFabricante: 'BH-030',
    codigoCompra: 'CP-629183',
    localizacao: 'G12B3A30',
  }
];

export default pecas;
