import { StyleSheet } from "react-native";
import Colors from '../../color'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 20, 
    paddingBottom: 10,
    backgroundColor: Colors.background,
  },
  contentHeader: {
    width: '100%',
    height: '12%', 
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20, 
  },
  textName: {
    fontSize: 26,
    fontWeight: 'bold',
    color: Colors.primary,
    letterSpacing: 2,
  },
  textDescription: {
    fontSize: 16, 
    fontStyle: 'italic',
    color: Colors.secondary,
    marginTop: 5,
  },
  contentInput: {
    width: '90%',
    paddingBottom: 10,
  },
  textInput: {
    fontSize: 16,
    color: Colors.text,
    marginBottom: 6, 
  },
  input: {
    width: '100%',
    height: 45, 
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingHorizontal: 15,
    fontSize: 16,
    backgroundColor: Colors.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  contentButton: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20, 
  },
  button: {
    width: '48%',
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: Colors.buttonPrimary,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
