import { StyleSheet } from "react-native";
import colors from '../../color';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    backgroundColor: colors.background,
    paddingTop: 40,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4, 
  },
  contentHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 5, 
  },
  textLogo: {
    fontSize: 30,
    fontWeight: 'bold',
    color: colors.text,
    letterSpacing: 1.5, 
  },
  welcomeText: {
    fontSize: 16,
    color: colors.secondary,
    fontWeight: '600',
  },
  contentSearch: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    marginTop: 15,
    backgroundColor: colors.lightBackground,
    borderRadius: 10, 
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  areaSearch: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  areaSearchInput: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 15,
  },
  input: {
    flex: 1,
    height: 45,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 15,
    borderColor: colors.border,
    backgroundColor: colors.white,
    fontSize: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  areaSearchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  areaAddButton: {
    marginLeft: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
});

export default styles;
